# Generated by Django 5.1.4 on 2025-04-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='conversationId',
            new_name='conversation_id',
        ),
    ]
