# Generated by Django 5.1.4 on 2025-03-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.productlisting'),
        ),
    ]
