# Generated by Django 5.1.4 on 2025-03-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_message_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.productrequest'),
        ),
    ]
