# Generated by Django 5.1.4 on 2025-03-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_message_product_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='product_request',
        ),
        migrations.AlterField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.productlisting'),
        ),
    ]
