# Generated by Django 5.1.4 on 2025-03-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_message_product_request_alter_message_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.productlisting'),
        ),
    ]
