# Generated by Django 5.1.4 on 2025-04-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_alter_post_file'),
        ('market', '0009_alter_message_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='new', max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.productlisting')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_made', to='Social.userprofile')),
            ],
        ),
    ]
