# Generated by Django 5.1.4 on 2025-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='productCategory',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('cereals', 'Cereals'), ('legumes', 'Legumes'), ('other', 'Other Category')], default='crop', max_length=20),
        ),
    ]
