# Generated by Django 5.1.4 on 2025-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_productlisting_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='productCategory',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('cereals', 'Cereals'), ('legumes', 'Legumes'), ('other', 'Other Category')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='productCategory',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('cereals', 'Cereals'), ('legumes', 'Legumes'), ('other', 'Other Category')], default='other', max_length=20),
        ),
    ]
