# Generated by Django 5.1.4 on 2025-04-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_productrequest_productcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='productCategory',
        ),
    ]
