# Generated by Django 5.1.4 on 2025-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_productrequest_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryMode',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=20),
        ),
    ]
