# Generated by Django 5.1.4 on 2025-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_order_deliverymode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
