# Generated by Django 5.1.4 on 2025-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_order_latitude_order_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
