# Generated by Django 5.1.4 on 2025-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_order_delivery_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('paid', 'Paid')], default='new', max_length=20),
        ),
    ]
