# Generated by Django 5.1.4 on 2025-05-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
