# Generated by Django 5.1.4 on 2025-05-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
