# Generated by Django 5.1.4 on 2025-03-21 08:02

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='uploads/'),
        ),
    ]
