# Generated by Django 5.1.4 on 2025-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='geocoded_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
