# Generated by Django 5.1.4 on 2025-04-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GAPSection',
        ),
    ]
